title = "Betterleaks"

# betterleaksMinVersion indicates the minimum betterleaks version required.
# If the running version is older, a warning will be logged.
betterleaksMinVersion = "1.6.0"

prefilter = '''
filter.matchesAny(get(attributes, "path", ""), [
r"""(?:^|/)\.env$""",
r"""^artifacts(?:/.*)?""",
r"""(?:^|/).*cache$""",
r"""(?:^|/).*img$""",
r"""(?:^|/).*\.vs$"""
])
'''

[extend]
useDefault = true
